name: primary
description: "Primary - Gestione Animali Domestici"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  lucide_icons_flutter: ^1.2.7
  provider: ^6.1.2
  intl: ^0.20.2
  path_provider: ^2.1.5
  watcher: ^1.1.1
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  table_calendar: ^3.2.0
  url_launcher: ^6.3.1
  flutter_local_notifications: ^19.0.0
  timezone: ^0.10.0
  pdf: ^3.11.3
  open_file: ^3.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/primary_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#F5E1A4"
  adaptive_icon_foreground: "assets/primary_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/image_placeholder.png
    - assets/welcome_cat.png
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/font/Quicksand-Light.ttf
          weight: 300
        - asset: assets/font/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/font/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/font/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/font/Quicksand-Bold.ttf
          weight: 700